### ISSUE TITLE
Update for new map Prison?

### ISSUE THREAD

**Issue by fleskebacon** [olli-e/ISRT#13]
Will there be an update for the new map? No big deal, I managed to add it manually, just wondering.

**Comment by olli-e** [comment]
No, just a new map does not justify the effort of going through it all. You can add it as standard map using the Mod.io-.ID "0" as in the number zero. Then the map will be added as standard and not custom map. This is all done using the map manager. During the next release, if neccessary because of major changes, I will add the map.
