### ISSUE TITLE
Player Names

### ISSUE THREAD

**Issue by lauriehowells** [olli-e/ISRT#14]
It would be handy to have the Control Center update at a regular interval, this would provide a better view on players, on the server, as a list... the Sever Monitor is very hard to read, as players are a continuous line.
Regard
Laurie h
Admin for Redback Gaming
redback.gaming.au@outlook.com

**Comment by olli-e** [comment]
Yeah I know and I struggled with this for a long time and it cost me easy 2 weeks of programming time to get this working for the monitor, because I then completely need to re-program this part. Having something updated regularly does require a complete new approach and that is an effort I'm currently not willing to spend; sorry for that m8.
